In [2]:
# data https://www.berlitz.com/blog/what-are-most-spoken-languages-africa

import pandas as pd

x = """3. Swahili
Total speakers: 80 million
swa
Latn
4. Hausa
Total speakers: 70 million
hau
Latn
5. Amharic
Total speakers: 57 million
amh
Ethi
6. Yoruba
Total speakers: 45 million
yor
Latn
7. Oromo
Total speakers: 40 million
orm
Latn
8. Igbo
Total speakers: 40 million
ibo
Latn
10. Zulu
Total speakers: 27 million
zul
Latn
11. Malagasy
Total speakers: 25 million
mlg
Other
12. Fula
Total speakers: 25 million
ful
Latn
13. Somali
Total speakers: 22 million
som
Other
14. Shona
Total speakers: 14 million
sna
Latn
15. Rundi (Kirundi)
Total speakers: 13 million
run
Latn
16. Kinyarwanda
Total speakers: 12 million
kin
Latn
17. Chichewa
Total speakers: 12 million
nya
Latn
18. Akan
Total speakers: 12 million
aka
Latn
19. Tigrinya
Total speakers: 9 million
tir
Other
20. Lingala
Total speakers: 8 million
lin
Latn"""

lines = x.split("\n")
df = []
row = []
for line in lines:
    row.append(line)
    if len(row) == 4:
        df.append(row)
        row = []

for i in range(len(df)):
    df[i][0] = df[i][0][df[i][0].find(" ")+1:].strip()
    df[i][1] = df[i][1].replace("Total speakers: ", "")
    df[i][1] = df[i][1].replace("million", "").strip()
    df[i][2] = df[i][2].strip()

df = pd.DataFrame(df, columns=("language", "n_speakers", "code", "script"))
df.to_csv("data/languages.csv")
df

           language n_speakers code script
0           Swahili         80  swa   Latn
1             Hausa         70  hau   Latn
2           Amharic         57  amh   Ethi
3            Yoruba         45  yor   Latn
4             Oromo         40  orm   Latn
5              Igbo         40  ibo   Latn
6              Zulu         27  zul   Latn
7          Malagasy         25  mlg  Other
8              Fula         25  ful   Latn
9            Somali         22  som  Other
10            Shona         14  sna   Latn
11  Rundi (Kirundi)         13  run   Latn
12      Kinyarwanda         12  kin   Latn
13         Chichewa         12  nya   Latn
14             Akan         12  aka   Latn
15         Tigrinya          9  tir  Other
16          Lingala          8  lin   Latn

In [9]:
x = df.head(5)
[f"{x}_{y}" for x, y in zip(x.code.tolist(), x.script.tolist())]

['swa_Latn', 'hau_Latn', 'amh_Ethi', 'yor_Latn', 'orm_Latn']

In [6]:
list(zip([1,2,3], [4,5,6]))

[(1, 4), (2, 5), (3, 6)]

In [40]:
# from https://commoncrawl.github.io/cc-crawl-statistics/plots/languages.html
# fular is not in common crawl
cc_languages = pd.read_csv("data/cc_language_stats.csv")
crawl = "CC-MAIN-2025-08"
cc_languages = cc_languages.query("crawl==@crawl")
for ix, row in df.iterrows():
    print(row["language"], row["code"] in cc_languages.primary_language.unique())

Swahili True
Hausa True
Amharic True
Yoruba True
Oromo True
Igbo True
Zulu True
Malagasy True
Fula False
Somali True
Shona True
Rundi (Kirundi) True
Kinyarwanda True
Chichewa True
Akan True
Tigrinya True
Lingala True

In [36]:
cc_languages.query("primary_language in @df.code.unique()").sort_values(by="pages", ascending=False)

                crawl primary_language   pages    urls  %pages/crawl
9426  CC-MAIN-2025-08              swa  222870  222378        0.0083
9418  CC-MAIN-2025-08              som  138936  138563        0.0052
9384  CC-MAIN-2025-08              mlg   92935   92547        0.0035
9299  CC-MAIN-2025-08              amh   83548   83068        0.0031
9343  CC-MAIN-2025-08              hau   72963   72583        0.0027
9368  CC-MAIN-2025-08              kin   56223   56085        0.0021
9455  CC-MAIN-2025-08              zul   34611   34494        0.0013
9452  CC-MAIN-2025-08              yor   21006   20956        0.0008
9435  CC-MAIN-2025-08              tir   19312   19159        0.0007
9416  CC-MAIN-2025-08              sna   16948   16838        0.0006
9351  CC-MAIN-2025-08              ibo   16824   16759        0.0006
9396  CC-MAIN-2025-08              nya   13670   13634        0.0005
9399  CC-MAIN-2025-08              orm   13290   13255        0.0005
9376  CC-MAIN-2025-08              lin    6909    6895        0.0003
9298  CC-MAIN-2025-08              aka    5071    5016        0.0002
9407  CC-MAIN-2025-08              run    1689    1687        0.0001

In [38]:
df.code.unique()

array(['swa', 'hau', 'amh', 'yor', 'orm', 'ibo', 'zul', 'mlg', 'ful',
       'som', 'sna', 'run', 'kin', 'nya', 'aka', 'tir', 'lin'],
      dtype=object)

In [ ]:
language_stats